# Generated by Django 5.0.3 on 2024-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktable',
            old_name='updated_at',
            new_name='completed_at',
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
