# Generated by Django 5.0.3 on 2024-03-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_rename_taskdata_tasktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='no_of_complete',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
